### ISSUE TITLE
Add tag to identify most recent version of cimg-azure image

### ISSUE THREAD

**Issue by Ian-Rowland-i2** [CircleCI-Public/cimg-azure#5]
The [cimg-azure](https://hub.docker.com/r/cimg/azure/tags) image does not have a `current/latest` tag.  This means that any reference to a specific version of that image will need to be manually updated to the latest version tag as-and-when it becomes available.

Please consider adding a tag such as  `current` or `latest` to the most recent image when it is published to ensure a mechanism exists to always pull the most recent version without having to update the tag manually.

![](https://stevelaskerblog.files.wordpress.com/2018/03/stabletagging.gif)

Gif Source: [Docker Tagging: Best practices for tagging and versioning docker images](https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/)

**Comment by BytesGuy** [comment]
@Ian-Rowland-i2 

Hi, as of right now we have no plans to support a `latest` or `current` tag for the `cimg` docker images.

The main reasons for this are summarised already in an issue post for the Go image (the same applies to all our `cimg` docker images), so I am linking this here:

https://github.com/CircleCI-Public/cimg-go/issues/103#issuecomment-726225831

Although this post is a bit old, our stance on this has not changed at this time.

I hope this explanation helps!
